# Generated by Django 5.0.1 on 2025-01-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('standard', models.IntegerField()),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('caste', models.CharField(default='OC', max_length=10)),
                ('phone_Number', models.BigIntegerField(max_length=10)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_name', models.CharField(max_length=100)),
                ('father_husband_name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=40)),
                ('phone_Number', models.BigIntegerField(max_length=10)),
            ],
        ),
    ]
